#### Day-1 (07-09-2026)

# PANDAS

# Def : Pandas is a  Open  Source  library designed for Data Manipulation and Analysis.
# Pandas is designed over the Numpy.

# Important list of operation in pandas

1. Data Structure creation  (Series  (ID array) , DataFrame (2d arrary))
2. Data  input and output (CSV, EXCEL, SQL , JSON)
3. Understanding the Dataset (head, tail , dtype....)
4. Data filtering  and indexing (loc, iloc,where()....)
5. Handi=ling of Missing values(NaN/NULL)
6. Removing Duplicate values
7. Handling inconsistant data
8. Data Transformation using apply(), map()
9. Aggregation and grouping
10. Time series operations
11. Basic Data Visualization

# Importing  and installation of pandas

# pip install pandas
# Above command  can  create problem with old numpy version 
# conda insatll pandas
3 conda commmand will update numpy also  with pandas . so no issue

In [4]:
import pandas as pd

In [3]:
pd.__version__

'2.3.3'

# 1. Data Structure creation (Series (1D array), DataFrame (2D array))

### Series(1D array)

In [5]:
# Create  Series
ser1 = pd.Series()
print(ser1)               # we use series function

Series([], dtype: object)

In [4]:
# convert  the list to series
list1 = [10, 20, 30, 40, 50]
ser2 = pd.Series(list1)
print(ser2)
print(type(ser2))

0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.core.series.Series'>

In [6]:
# convert  the list to series 
# hetroginous elements
# in pandas strings are represented as object
# IMP: In series ,all elements have the same datatype
list1 = [10, 20, 30, 40, 50, "Hello"]
ser2 = pd.Series(list1)
print(ser2)
print(type(ser2))

0       10
1       20
2       30
3       40
4       50
5    Hello
dtype: object
<class 'pandas.core.series.Series'>

In [8]:
# Convert tuple to Series
tuple1 = (10, 20, 30, 40, 50)
ser2 = pd.Series(tuple1)
print(ser2)
print(type(ser2))

0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.core.series.Series'>

In [6]:
tuple1 = (10, 20, 30, 40, 50)
ser2 = pd.Series(tuple1)
print(ser2)
print(type(ser2))
print(ser2[2])

0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.core.series.Series'>
30

In [ ]:
tuple1 = (10, 20, 30, 40, 50)
ser2 = pd.Series(tuple1)
print(ser2)
print(type(ser2))
print(ser2[2])
print(ser2[-2])

# In Pandas Series , direct negative indexing not allowed.

In [11]:
# Set cannot be converted  to pandas series
# Set i unordered and series is ordered, so no conversion
set1 = {10, 20, 30, 40, 50}
ser2 = pd.Series(set1)
print(ser2)

TypeError: 'set' type is unordered

In [12]:
# Convert the numpy array into Series

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
print(arr1, type(arr1))

[10 20 30 40 50] <class 'numpy.ndarray'>

In [13]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
print(arr1, type(arr1))
ser3 = pd.Series(arr1)
print(arr1, type(ser1))

[10 20 30 40 50] <class 'numpy.ndarray'>
[10 20 30 40 50] <class 'pandas.core.series.Series'>

In [15]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
print(arr1, type(arr1))
ser3 = pd.Series(arr1 , index = ['a' , 'b', 'c', 'd', 'e'])
print(ser3, type(ser3))
print(ser3['a'])

[10 20 30 40 50] <class 'numpy.ndarray'>
a    10
b    20
c    30
d    40
e    50
dtype: int64 <class 'pandas.core.series.Series'>
10

In [32]:
# Update operation on series
ser2[3] = 100000

# insert new value
ser2[5] = 2000
ser2['a'] = 5000
ser2[60] = 7000
ser2[3.4] = 9000
print(ser2)

0          10
2          30
3      100000
4          50
5        2000
a        5000
60       7000
3.4      9000
dtype: int64

In [30]:
# delete elements from  series
ser2 = ser2.drop(1)
ser2

0          10
2          30
3      100000
4          50
5        2000
a        5000
60       7000
3.4      9000
dtype: int64

##### Day: 08/09/2026

# Data Frame is a 2D array , store data in from of matrix.

In [10]:
import pandas as pd

In [11]:
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [4]:
# converting list to data frame 
fruits_list = ["AratiPandu", "MamadiPandu", "KamalaPandu", "DrakshaPandu"]
df = pd.DataFrame(fruits_list, columns = ["Fruit Name"])
print(df)

     Fruit Name
0    AratiPandu
1   MamadiPandu
2   KamalaPandu
3  DrakshaPandu

In [5]:
fruits_list = ["AratiPandu", "MamadiPandu", "KamalaPandu", "DrakshaPandu"]
df = pd.DataFrame(fruits_list, columns = ["Fruit Name"])
df

     Fruit Name
0    AratiPandu
1   MamadiPandu
2   KamalaPandu
3  DrakshaPandu

In [6]:
# converting 2D list DataFrame
fruits_list = [["AratiPandu",40], ["MamadiPandu",1000], ["KamalaPandu",10], ["DrakshaPandu",120]]
df = pd.DataFrame(fruits_list, columns = ["Fruit Name", "Price"])
df

     Fruit Name  Price
0    AratiPandu     40
1   MamadiPandu   1000
2   KamalaPandu     10
3  DrakshaPandu    120

In [7]:
# created 3 columns dataframe(list of list)
fruits_list = [["AratiPandu",40,100], ["MamadiPandu",1000,200], ["KamalaPandu",10,1000], ["DrakshaPandu",120,100]]
df = pd.DataFrame(fruits_list, columns = ["Fruit Name", "Price", "Discount"])
df

     Fruit Name  Price  Discount
0    AratiPandu     40       100
1   MamadiPandu   1000       200
2   KamalaPandu     10      1000
3  DrakshaPandu    120       100

In [14]:
# created 3 columns dataframe(list of tuple)
fruits_list = [("AratiPandu",40,100), ("MamadiPandu",1000,200), ("KamalaPandu",10,1000), ("DrakshaPandu",120,-100)]
df = pd.DataFrame(fruits_list, columns = ["Fruit Name", "Price", "Discount"])
df

     Fruit Name  Price  Discount
0    AratiPandu     40       100
1   MamadiPandu   1000       200
2   KamalaPandu     10      1000
3  DrakshaPandu    120      -100

In [8]:
# creating DataFrame from dictionary
student_data = {
    "Name" : ["Shiva", "Niranjan", "Suresh", "Akash", "Lahari", "Rakesh"],
    "Salary" : [40,50,60,15,25,100],
    "Study_time" : [12,14, 16, 1, 5, 24]
}
df1 = pd.DataFrame(student_data)
df1

       Name  Salary  Study_time
0     Shiva      40          12
1  Niranjan      50          14
2    Suresh      60          16
3     Akash      15           1
4    Lahari      25           5
5    Rakesh     100          24

In [15]:
# convert the set of tuple into DataFrame
fruits_list = [("AratiPandu",40,100), ("MamadiPandu",1000,200), ("KamalaPandu",10,1000), ("DrakshaPandu",120,-100)]
df = pd.DataFrame(fruits_list, columns = ["Fruit Name", "Price", "Discount"])
df

     Fruit Name  Price  Discount
0    AratiPandu     40       100
1   MamadiPandu   1000       200
2   KamalaPandu     10      1000
3  DrakshaPandu    120      -100

In [18]:
# Creating DataFrame from set of set 
# In set, we cannot store the mutable items
# In set, only immutable items   can be store
fruits_list = {{"AratiPandu", 40, 100} , {"MamadiPandu",1000,200}, {"KamalaPandu",10,1000}, {"DrakshPandu",120,-100}}
df = pd.DataFrame(fruits_list, columns = ["Fruit Name", "Price", "Discount"])
df

TypeError: unhashable type: 'set'

In [19]:
# Creating DataFrame from set of list 

fruits_list = {["AratiPandu", 40, 100] , ["MamadiPandu",1000,200], ["KamalaPandu",10,1000], ["DrakshPandu",120,-100]}
df = pd.DataFrame(fruits_list, columns = ["Fruit Name", "Price", "Discount"])
df

TypeError: unhashable type: 'list'

## 2.Data input and output (CSV,EXCEL,SQL,JSON)

In [8]:
# importing data from CSV file

import os 
os.getcwd()

'C:\\Users\\gurushankar'

In [12]:
# import a CSV file as DataFrame
df_csv = pd.read_csv("CSV_data.csv")
df_csv

       Name   Age         Profession  Salary                    Favorite Quote
0      John  25.0  Software Engineer   80000            Keep calm and code on!
1     Alice   NaN             Doctor  120000           Trust me, I'm a doctor!
2     Rocky   NaN              Boxer   50000                 Eye of the tiger!
3  Sherlock  40.0          Detective  150000  It's elementary, my dear Watson.
4  Mr. Bean  50.0           Comedian   10000                   Why so serious?
5  Mr. Bean  50.0           Comedian   10000                   Why so serious?

In [30]:
# import excel file as a DataFrame
df_excel=pd.read_excel("Excel_data.xlsx")
df_excel

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [31]:
# export the  data back to csv  and excel file
df_csv.to_excel("Da22_excel.xlsx",index=False)
df_excel.to_csv("Da22_CSV.csv",index=False)

In [ ]:
day-3

In [32]:
df_excel

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [26]:
# reading and writing inn a sql
import sqlite3
# creating a database if it don't exist
conn = sqlite3.connect("shiva_da22.db")

In [33]:
# creating a table and strating the dataframe data inside it
df_excel.to_sql("prof_table",conn,if_exists='replace')

500

In [15]:
# reading the data from sql table to df
df =pd.read_sql('select * from prof_table',conn)
df

,index,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,0,1,olivia,23.0,Teacher,184518,0
1,1,2,sophia,20.0,Boxer,119572,2
2,2,3,jake,38.0,Scientist,174897,1
3,3,4,Rocky,56.0,Chef,117920,2
4,4,4,Rocky,56.0,Chef,117920,1
...,...,...,...,...,...,...,...
495,495,496,John,45.0,Boxer,137929,0
496,496,497,Sherlock,46.0,Boxer,39870,6
497,497,498,Sherlock,47.0,Detective,165951,5
498,498,499,Olivia,55.0,Comedian,192618,5
499,499,500,Sherlock,59.0,Software Engineer,194886,28

In [19]:
# impoting data from JSON file 
df_json = pd.read_json('json_data.json')
df_json

,order_id,customer_name,food_item,delivery_boy,rating,delivery_time_min
0,101,Ramu,Idli Burger,Speed Shankar,5,15
1,102,Priya,Dosa Pizza,Late Laxman,2,60
2,103,Dinesh,Paneer Sambar,Turbo Thambi,4,25
3,104,Lachu,Mango Maggi,Round Robin,1,90
4,105,Meena,Coconut Coffee,Careless Kannan,3,40

In [20]:
# exporting data from dataframe to json file 
df_json.to_json('food_data.json')

## 3. understading the data set (head,tail,dtype,.....)

In [25]:
# view the data with head(),tail() functions
# head(x) function is used to accessing top x records
# head() by default shows the 5 records
df_excel.head(10)

   ID       Name   Age   Profession  salary  Marriage_proposal_count
0   1     olivia  23.0      Teacher  184518                        0
1   2  sophia     20.0        Boxer  119572                        2
2   3       jake  38.0    Scientist  174897                        1
3   4      Rocky  56.0         Chef  117920                        2
4   4      Rocky  56.0         Chef  117920                        1
5   4      Rocky  56.0         Chef  117920                        3
6   4      Rocky  56.0         Chef  117920                       11
7   4      Rocky  56.0         Chef  117920                        2
8   4      Rocky  56.0         Chef  117920                        2
9   4      Rocky  56.0         Chef  117920                        3

In [26]:
# tail(x) function is used to accessing bottom x records
# tail() by default shows the 5 records
df_excel.tail(10)

      ID      Name   Age         Profession  salary  Marriage_proposal_count
490  491      John  57.0              Pilot  154180                        0
491  492      Emma  34.0             Artist  145412                        1
492  493      John  55.0             Artist   57720                        2
493  494    Sophia  39.0             Doctor  174500                        0
494  495     Rocky  27.0             Doctor   46975                        0
495  496      John  45.0              Boxer  137929                        0
496  497  Sherlock  46.0              Boxer   39870                        6
497  498  Sherlock  47.0          Detective  165951                        5
498  499    Olivia  55.0           Comedian  192618                        5
499  500  Sherlock  59.0  Software Engineer  194886                       28

In [27]:
df_excel.shape

(500, 6)

In [28]:
# shows the single column
df_excel['Name']

0         olivia
1      sophia
2           jake
3          Rocky
4          Rocky
         ...
495         John
496     Sherlock
497     Sherlock
498       Olivia
499     Sherlock
Name: Name, Length: 500, dtype: object

In [29]:
df_excel.Name

0         olivia
1      sophia
2           jake
3          Rocky
4          Rocky
         ...
495         John
496     Sherlock
497     Sherlock
498       Olivia
499     Sherlock
Name: Name, Length: 500, dtype: object

In [34]:
df_excel['Profession']

0                Teacher
1                  Boxer
2              Scientist
3                   Chef
4                   Chef
             ...
495                Boxer
496                Boxer
497            Detective
498             Comedian
499    Software Engineer
Name: Profession, Length: 500, dtype: object

In [35]:
df_excel[['Name','Profession']]

          Name         Profession
0       olivia            Teacher
1    sophia                 Boxer
2         jake          Scientist
3        Rocky               Chef
4        Rocky               Chef
..         ...                ...
495       John              Boxer
496   Sherlock              Boxer
497   Sherlock          Detective
498     Olivia           Comedian
499   Sherlock  Software Engineer

[500 rows x 2 columns]

In [36]:
# printing multiple columns
df_excel[['Name','Profession','salary']]

          Name         Profession  salary
0       olivia            Teacher  184518
1    sophia                 Boxer  119572
2         jake          Scientist  174897
3        Rocky               Chef  117920
4        Rocky               Chef  117920
..         ...                ...     ...
495       John              Boxer  137929
496   Sherlock              Boxer   39870
497   Sherlock          Detective  165951
498     Olivia           Comedian  192618
499   Sherlock  Software Engineer  194886

[500 rows x 3 columns]

In [37]:
df_rename=df_excel.rename(columns ={'Name':'peru','Profession':'Vruthi'})
df_rename

      ID       peru   Age             Vruthi  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [38]:

# print all the column names 
df_rename.columns

Index(['ID', 'peru', 'Age', 'Vruthi', 'salary', 'Marriage_proposal_count'], dtype='object')

## creating new column in the dataframe

In [39]:
#  here rank() function is a pandas function
# rank() function is giving rank-1 to minmum salary and higher rank value to higher salary
df_excel['rank'] = df_excel['salary'].rank(ascending =False)
df_excel.sort_values('rank')

,ID,Name,Age,Profession,salary,Marriage_proposal_count,rank
436,437,Sherlock,52.0,Boxer,199529,3,1.0
65,66,Emma,57.0,Pilot,199317,1,2.0
132,133,Rocky,31.0,Doctor,198978,8,3.0
167,168,Mr. Bean,44.0,Comedian,198847,14,4.0
474,475,Sophia,30.0,Doctor,198653,1,5.0
...,...,...,...,...,...,...,...
284,285,Jake,46.0,Detective,30971,1,496.0
329,330,Sherlock,40.0,Scientist,30905,0,497.0
398,399,Rocky,25.0,Scientist,30659,5,498.0
90,91,Rocky,43.0,Software Engineer,30407,10,499.0
213,214,Sherlock,21.0,Chef,30164,2,500.0

In [40]:
# droping the column
# axis =1 : delete the column
# axis =0 : delete the row
df_excel=df_excel.drop(['rank'],axis=1)
df_excel

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

## Replace a value in dataframe

In [41]:
df=df_excel
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [42]:
# repalce all the olivia in name column with cherry
df['Name'] = df.Name.replace('olivia','cherry')
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     cherry  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [43]:
# replacing multiple values
df['Name'] = df.Name.replace({'cherry':'shiva','Rocky':'vedhu'})

# replacing values from multiple columns together
# inplace = true : to perform the task without taking extra space  

df= df.replace({'shiva':'AA','Teacher':'hero'})   # or df.replace({'shiva':'AA','Teacher':'hero'}, inplace  = True)
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1         AA  23.0               hero  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      vedhu  56.0               Chef  117920                        2
4      4      vedhu  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [44]:
# dtypes are used to check the datatype of all the columns
# in pandas, strings are represented with object
df.dtypes

ID                           int64
Name                        object
Age                        float64
Profession                  object
salary                       int64
Marriage_proposal_count      int64
dtype: object

## convert datatype

In [45]:
# 
df['Name'] = df['Name'].astype('string')
df.dtypes

ID                                  int64
Name                       string[python]
Age                               float64
Profession                         object
salary                              int64
Marriage_proposal_count             int64
dtype: object

In [46]:

df['salary'] = df['salary'].astype('float')
df.dtypes

ID                                  int64
Name                       string[python]
Age                               float64
Profession                         object
salary                            float64
Marriage_proposal_count             int64
dtype: object

In [47]:
# printing the columns which is having specific datatypes numarical columns
df.select_dtypes(include = ['int','float'])

      ID   Age    salary  Marriage_proposal_count
0      1  23.0  184518.0                        0
1      2  20.0  119572.0                        2
2      3  38.0  174897.0                        1
3      4  56.0  117920.0                        2
4      4  56.0  117920.0                        1
..   ...   ...       ...                      ...
495  496  45.0  137929.0                        0
496  497  46.0   39870.0                        6
497  498  47.0  165951.0                        5
498  499  55.0  192618.0                        5
499  500  59.0  194886.0                       28

[500 rows x 4 columns]

In [48]:
# string columns or catagrical columns
df.select_dtypes(include = ['string','object'])

          Name         Profession
0           AA               hero
1    sophia                 Boxer
2         jake          Scientist
3        vedhu               Chef
4        vedhu               Chef
..         ...                ...
495       John              Boxer
496   Sherlock              Boxer
497   Sherlock          Detective
498     Olivia           Comedian
499   Sherlock  Software Engineer

[500 rows x 2 columns]

In [49]:
# give name of all the columns which are string type 
df.select_dtypes(include = ['string','object']).columns

Index(['Name', 'Profession'], dtype='object')

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       500 non-null    int64
 1   Name                     500 non-null    string
 2   Age                      492 non-null    float64
 3   Profession               500 non-null    object
 4   salary                   500 non-null    float64
 5   Marriage_proposal_count  500 non-null    int64
dtypes: float64(2), int64(2), object(1), string(1)
memory usage: 23.6+ KB

In [51]:
# query: print all the unique profession
df.Profession.unique()

array(['hero', '      Boxer', 'Scientist', 'Chef', 'Doctor', 'Artist',
       'Comedian', 'Software Engineer', 'Detective', 'Pilot'],
      dtype=object)

In [52]:
# nunique is telling number if unique in this profession 
df.Profession.nunique()

10

In [53]:
# query: how many people are boxer in this dataset
df.Profession.value_counts()

Profession
Chef                 58
Scientist            54
      Boxer          53
Pilot                53
Comedian             52
Software Engineer    51
Doctor               48
hero                 45
Detective            45
Artist               41
Name: count, dtype: int64

In [54]:
# describe statistical information 
# bydefault , describe() works on numerical columns
df.describe()

               ID         Age         salary  Marriage_proposal_count
count  500.000000  492.000000     500.000000                500.00000
mean   250.458000   40.810976  115602.828000                  4.02600
std    144.552978   11.790553   49404.366846                  5.25362
min      1.000000   20.000000   30164.000000                  0.00000
25%    125.750000   31.000000   74964.750000                  1.00000
50%    250.500000   40.500000  117920.000000                  3.00000
75%    375.250000   51.000000  160579.500000                  5.00000
max    500.000000   60.000000  199529.000000                 40.00000

In [55]:
df.describe(include ='int')

               ID  Marriage_proposal_count
count  500.000000                500.00000
mean   250.458000                  4.02600
std    144.552978                  5.25362
min      1.000000                  0.00000
25%    125.750000                  1.00000
50%    250.500000                  3.00000
75%    375.250000                  5.00000
max    500.000000                 40.00000

In [56]:
# describing string/object columns
df.describe(include =['object','string'])

            Name Profession
count        500        500
unique        13         10
top     Sherlock       Chef
freq          61         58


### 4. data flitering and indexing (loc,iloc,where()....)

In [57]:
# fliter all the recordes where salary > 100000
df[df.salary>100000]

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,AA,23.0,hero,184518.0,0
1,2,sophia,20.0,Boxer,119572.0,2
2,3,jake,38.0,Scientist,174897.0,1
3,4,vedhu,56.0,Chef,117920.0,2
4,4,vedhu,56.0,Chef,117920.0,1
...,...,...,...,...,...,...
493,494,Sophia,39.0,Doctor,174500.0,0
495,496,John,45.0,Boxer,137929.0,0
497,498,Sherlock,47.0,Detective,165951.0,5
498,499,Olivia,55.0,Comedian,192618.0,5
499,500,Sherlock,59.0,Software Engineer,194886.0,28

In [58]:
# fliter all the records where salary >100000 & salary < 15000000
df[(df.salary < 100000) & (df.salary < 150000)]

      ID      Name   Age         Profession   salary  Marriage_proposal_count
10    11     vedhu   NaN             Doctor  75543.0                        5
13    14      John  46.0             Artist  43078.0                       12
15    16  Sherlock  30.0              Boxer  57774.0                        0
23    24  Sherlock  42.0              Boxer  92995.0                        2
26    27     Alice  48.0              Pilot  99949.0                        4
..   ...       ...   ...                ...      ...                      ...
488  489      Emma  21.0  Software Engineer  92013.0                        2
489  490      John  56.0          Scientist  41192.0                        7
492  493      John  55.0             Artist  57720.0                        2
494  495     vedhu  27.0             Doctor  46975.0                        0
496  497  Sherlock  46.0              Boxer  39870.0                        6

[196 rows x 6 columns]

In [64]:
# query: fliter all the records where salary >100000 /(OR)(salary < 100000
df[(df.salary < 100000) | (df.salary > 150000)]

      ID      Name   Age         Profession    salary  Marriage_proposal_count
0      1        AA  23.0               hero  184518.0                        0
2      3      jake  38.0          Scientist  174897.0                        1
10    11     vedhu   NaN             Doctor   75543.0                        5
11    12      Jake   NaN             Artist  174780.0                        5
13    14      John  46.0             Artist   43078.0                       12
..   ...       ...   ...                ...       ...                      ...
494  495     vedhu  27.0             Doctor   46975.0                        0
496  497  Sherlock  46.0              Boxer   39870.0                        6
497  498  Sherlock  47.0          Detective  165951.0                        5
498  499    Olivia  55.0           Comedian  192618.0                        5
499  500  Sherlock  59.0  Software Engineer  194886.0                       28

[349 rows x 6 columns]

In [65]:
# query: find the person record who is getting highest salary.
# hint :max()
max(df.salary)

199529.0

In [66]:
df.salary.max()

199529.0

## day-5 11/09/2026

In [50]:
# query: find the person record who is getting highest salary.
# hint :max()
import pandas as pd
df = pd.read_excel("Excel_data.xlsx")
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [51]:
# query: find the person record who is getting highest salary.
max(df.salary)

199529

In [52]:
df[df.salary > 100000]

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
493  494     Sophia  39.0             Doctor  174500                        0
495  496       John  45.0              Boxer  137929                        0
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[304 rows x 6 columns]

In [53]:
df[df.salary == df.salary.max()]

      ID      Name   Age   Profession  salary  Marriage_proposal_count
436  437  Sherlock  52.0        Boxer  199529                        3

In [54]:
# query: find the person record who is getting lowest salary.
# Hint: min
min(df.salary)

30164

In [55]:
df.salary == df.salary.min()

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Name: salary, Length: 500, dtype: bool

In [56]:
df[df.salary == df.salary.min()]

      ID      Name   Age Profession  salary  Marriage_proposal_count
213  214  Sherlock  21.0       Chef   30164                        2

In [57]:
# Query : Print just the  Name, Age, salary of the person having max salary
df[df.salary == df.salary.max()]

      ID      Name   Age   Profession  salary  Marriage_proposal_count
436  437  Sherlock  52.0        Boxer  199529                        3

In [58]:
df[df.salary == df.salary.max()].Name

436    Sherlock
Name: Name, dtype: object

In [59]:
# Query : print just the Name Age salary of the person having max salary
df[df.salary == df.salary.max()][["Name", "Age","salary"]]

         Name   Age  salary
436  Sherlock  52.0  199529

In [60]:
df.Age

0      23.0
1      20.0
2      38.0
3      56.0
4      56.0
       ...
495    45.0
496    46.0
497    47.0
498    55.0
499    59.0
Name: Age, Length: 500, dtype: float64

In [61]:
df["Age"]

0      23.0
1      20.0
2      38.0
3      56.0
4      56.0
       ...
495    45.0
496    46.0
497    47.0
498    55.0
499    59.0
Name: Age, Length: 500, dtype: float64

In [62]:
df[["Name", "Age","salary"]]

          Name   Age  salary
0       olivia  23.0  184518
1    sophia     20.0  119572
2         jake  38.0  174897
3        Rocky  56.0  117920
4        Rocky  56.0  117920
..         ...   ...     ...
495       John  45.0  137929
496   Sherlock  46.0   39870
497   Sherlock  47.0  165951
498     Olivia  55.0  192618
499   Sherlock  59.0  194886

[500 rows x 3 columns]

In [63]:
### where(): used for filtering the data
# where() function returns NaN in place of those values
# which don't satisfied the condition
df1 = df.copy()

df1 = df1.Age.where(df1.Age > 50)

df1

0       NaN
1       NaN
2       NaN
3      56.0
4      56.0
       ...
495     NaN
496     NaN
497     NaN
498    55.0
499    59.0
Name: Age, Length: 500, dtype: float64

In [64]:
# if you don't want NaN records
df[df.Age > 50]

      ID      Name   Age         Profession  salary  Marriage_proposal_count
3      4     Rocky  56.0               Chef  117920                        2
4      4     Rocky  56.0               Chef  117920                        1
5      4     Rocky  56.0               Chef  117920                        3
6      4     Rocky  56.0               Chef  117920                       11
7      4     Rocky  56.0               Chef  117920                        2
..   ...       ...   ...                ...     ...                      ...
489  490      John  56.0          Scientist   41192                        7
490  491      John  57.0              Pilot  154180                        0
492  493      John  55.0             Artist   57720                        2
498  499    Olivia  55.0           Comedian  192618                        5
499  500  Sherlock  59.0  Software Engineer  194886                       28

[126 rows x 6 columns]

In [71]:
### where(): used for filtering the data
# where() function returns NaN in place of those values
# which don't satisfied the condition
df1 = df.copy()
df1 = df1.Age.where(df1.Age > 50)
df1

0       NaN
1       NaN
2       NaN
3      56.0
4      56.0
       ...
495     NaN
496     NaN
497     NaN
498    55.0
499    59.0
Name: Age, Length: 500, dtype: float64

In [72]:
df1 = df.copy()
df1 = df1.Age.where(df1.Age > 50,100)
df1

0      100.0
1      100.0
2      100.0
3       56.0
4       56.0
       ...
495    100.0
496    100.0
497    100.0
498     55.0
499     59.0
Name: Age, Length: 500, dtype: float64

In [73]:
# if you dont want NaN records
df[df.Age > 50]

      ID      Name   Age         Profession  salary  Marriage_proposal_count
3      4     Rocky  56.0               Chef  117920                        2
4      4     Rocky  56.0               Chef  117920                        1
5      4     Rocky  56.0               Chef  117920                        3
6      4     Rocky  56.0               Chef  117920                       11
7      4     Rocky  56.0               Chef  117920                        2
..   ...       ...   ...                ...     ...                      ...
489  490      John  56.0          Scientist   41192                        7
490  491      John  57.0              Pilot  154180                        0
492  493      John  55.0             Artist   57720                        2
498  499    Olivia  55.0           Comedian  192618                        5
499  500  Sherlock  59.0  Software Engineer  194886                       28

[126 rows x 6 columns]

## indexing: loc &  iloc

In [74]:
# loc & iloc is used for filtering
# these helps to select particualr ROW & COLUMN in the dataframe

In [76]:
# Query: print records 1 to 4, and columns ID, name, Age Only
df.loc[1:4,'ID': 'Age']   # df.loc[start_row : end_row, col_start : col_end]

   ID       Name   Age
1   2  sophia     20.0
2   3       jake  38.0
3   4      Rocky  56.0
4   4      Rocky  56.0

## INTERVIEW Question 
Q1. What is the difference between loc and iloc?
A. - In loc columns are passed with their Names but in iloc columns are passed as index
   - iloc is  easy to use due to index usage
   - iloc [start_row : end_row-1, col_start : col_end-1]
   - iloc is ittle faster than the loc

In [81]:
# Query: Print records 10 to 40 , and columns Name:Profession Only
df.loc[10:40, "Name" : "Profession"]

        Name   Age         Profession
10     Rocky   NaN             Doctor
11      Jake   NaN             Artist
12    Olivia  22.0           Comedian
13      John  46.0             Artist
14      Jake  40.0               Chef
15  Sherlock  30.0              Boxer
16      Jake  46.0             Artist
17      Jake  53.0  Software Engineer
18     Rocky  25.0           Comedian
19  Sherlock  40.0          Detective
20  Sherlock  40.0          Detective
21      John  41.0          Scientist
22      John  41.0          Scientist
23  Sherlock  42.0              Boxer
24    Olivia  60.0          Detective
25    Olivia  53.0          Detective
26     Alice  48.0              Pilot
27  Sherlock  55.0          Scientist
28     Alice  21.0               Chef
29     Alice  21.0               Chef
30     Alice  30.0            Teacher
31    Olivia  30.0             Doctor
32  Mr. Bean  27.0             Artist
33    Olivia  45.0           Comedian
34  Sherlock  46.0               Chef
35  Mr. Bean  44.0           Comedian
36     Rocky  57.0            Teacher
37  Mr. Bean  32.0          Scientist
38      John  27.0  Software Engineer
39    Olivia  60.0  Software Engineer
40     Alice  52.0               Chef

In [82]:
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [83]:
df.columns

Index(['ID', 'Name', 'Age', 'Profession', 'salary', 'Marriage_proposal_count'], dtype='object')

## iloc

In [84]:
# Query : print records 1 to 4, and columns ID, name, Age Only
df.iloc[1:5, 0:3]

   ID       Name   Age
1   2  sophia     20.0
2   3       jake  38.0
3   4      Rocky  56.0
4   4      Rocky  56.0